### PR TITLE
Added concession_interceptor

### PR DESCRIPTION
**Pull request by C-Frohburg**
Interceptor displays multiple instances of the same item on one line instead of as a list.
Displayed in the form: Name: XXXX, Quantity: XXXX, Price: XXXX, Amount: XXXX

Also fixed a bug regarding updating the concession sales database

### CODE REVIEW

**Review by LukeMaher98 — CHANGES_REQUESTED** [review]
This isnt integrated with the memento method; the non-intercepted states are being saved, as seen utilising the undo/redo functionality. 

Removing items from basket doesnt work with amalgamated listings, shows "No items to remove"

Also seems that if you add an item in increments of 1, it wont show up until the number of that item surpasses the maximum of other listed items

**Comment by LukeMaher98** [comment]
> This isnt integrated with the memento method; the non-intercepted states are being saved, as seen utilising the undo/redo functionality.
> 
> Removing items from basket doesnt work with amalgamated listings, shows "No items to remove"
> 
> Also seems that if you add an item in increments of 1, it wont show up until the number of that item surpasses the maximum of other listed items

For the memento I think you just need to have the interceptor also activated when a state is loaded from memory as opposed to only when a new state is added

**Review by LukeMaher98 — APPROVED** [review]
Yeah, all my issues addressed. Looks GTG

**Review by LukeMaher98 — COMMENTED** [review]
Just resolve the merge conflicts

**Review by Lennaayy — APPROVED** [review]
*Chef's Kiss*

**Pull request merged**
